# Generated by Django 5.0.14 on 2025-07-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_see_all_borrowed_books', 'View all borrowed books'), ('can_renew', 'Renew the due back date'))},
        ),
    ]
