# Generated by Django 5.2.7 on 2025-10-28 22:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_cover_image_alter_author_date_of_death_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name'), models.F('date_of_birth'), models.F('date_of_death'), name='unique_author_case_insensitive', violation_error_message='Author with the same name and life dates already exists.'),
        ),
    ]
