# Generated by Django 5.2.7 on 2025-11-06 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_author_unique_author_case_insensitive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'author', 'summary'), name='unique_book_per_author', violation_error_message='A book with the same title, author, and summary already exists.'),
        ),
        migrations.AddConstraint(
            model_name='bookinstance',
            constraint=models.UniqueConstraint(fields=('book', 'imprint', 'borrower'), name='unique_copy_per_borrower'),
        ),
    ]
